# Generated by Django 4.2.4 on 2023-09-07 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('age', models.IntegerField(default=0)),
                ('about_me', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=30)),
                ('user_photo', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('date_added_product', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('date_added_order', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_1.client')),
                ('orders', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp_1.product')),
            ],
        ),
    ]
