# Generated by Django 4.2.4 on 2023-09-02 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_added_order',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 22, 9, 0, 109396, tzinfo=datetime.timezone.utc)),
        ),
    ]
