# Generated by Django 4.2.4 on 2023-09-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
