# Generated by Django 4.2.4 on 2023-09-02 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0002_alter_order_date_added_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_added_order',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 22, 15, 4, 434783, tzinfo=datetime.timezone.utc)),
        ),
    ]
