# Generated by Django 4.2.4 on 2023-09-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0003_alter_order_date_added_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_added_order',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
